/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import controller.PersonalController;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import model.Model_Laporan;
import model.Personaldata;
import org.hibernate.SessionFactory;
import tools.HibernateUtil;
public class cv_kandidat extends javax.swing.JFrame {
    SessionFactory sf;
    private TableRowSorter<TableModel> rowSorter;
    private final PersonalController controller;
    
    Model_Laporan model = new Model_Laporan(sf);
    public String id;
    
    public cv_kandidat() {
        initComponents();
        controller = new PersonalController(HibernateUtil.getSessionFactory());
        bindingOrganization(controller.getAll());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtIdKandidat = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDataKandidat = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtIdKandidat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdKandidatActionPerformed(evt);
            }
        });
        txtIdKandidat.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtIdKandidatPropertyChange(evt);
            }
        });
        txtIdKandidat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtIdKandidatKeyReleased(evt);
            }
        });

        jButton1.setText("Report");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tblDataKandidat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblDataKandidat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDataKandidatMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDataKandidat);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txtIdKandidat, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 724, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdKandidat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdKandidatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdKandidatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdKandidatActionPerformed

    private void txtIdKandidatPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtIdKandidatPropertyChange
         // TODO add your handling code here:
    }//GEN-LAST:event_txtIdKandidatPropertyChange

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            model.Tampilkan(this);
        } catch (SQLException ex) {
            Logger.getLogger(cv_kandidat.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtIdKandidatKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdKandidatKeyReleased
         // TODO add your handling code here:
         if (txtIdKandidat.getText() != null) {
            id = txtIdKandidat.getText();
        }
    }//GEN-LAST:event_txtIdKandidatKeyReleased

    private void tblDataKandidatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDataKandidatMouseClicked
         // TODO add your handling code here:
         int row = tblDataKandidat.getSelectedRow();
         txtIdKandidat.setText(tblDataKandidat.getValueAt(row, 1)+" ");
         id = (String) tblDataKandidat.getValueAt(row, 1);
    }//GEN-LAST:event_tblDataKandidatMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cv_kandidat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cv_kandidat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cv_kandidat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cv_kandidat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cv_kandidat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDataKandidat;
    public javax.swing.JTextField txtIdKandidat;
    // End of variables declaration//GEN-END:variables
    
    private void bindingOrganization(List<Object> personal) {
        String[] header = {"No", "ID Personal", "Nama Personal", "Date of birth", "Nationality", "Marital Status", "Gender", "Phone Number", "Email", "Photo"};
        String[][] data = new String[personal.size()][header.length];
        int i = 0;
        for (Object object : personal) {
            Personaldata organization = (Personaldata) object;
            data[i][0] = (i + 1) + "";
            data[i][1] = organization.getIdpersonal().toString();
            data[i][2] = organization.getName();
            data[i][3] = organization.getDateofbirth().toString();
            data[i][4] = organization.getNationality();
            data[i][5] = organization.getMaritalstatus();
            data[i][6] = organization.getGender();
            data[i][7] = organization.getPhonenumber();
            data[i][8] = organization.getEmail();
            data[i][9] = organization.getFoto();
            i++;
        }
        tblDataKandidat.setModel(new DefaultTableModel(data, header));
        this.rowSorter = new TableRowSorter<>(tblDataKandidat.getModel());
    }
}
