
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.BorderLayout;
import java.io.File;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JInternalFrame;
//import net.sf.jasperreports.engine.JasperCompileManager;
//import net.sf.jasperreports.engine.JasperFillManager;
//import net.sf.jasperreports.engine.JasperPrint;
//import net.sf.jasperreports.engine.JasperReport;
//import net.sf.jasperreports.engine.design.JasperDesign;
//import net.sf.jasperreports.engine.xml.JRXmlLoader;
//import net.sf.jasperreports.view.JRViewer;
import org.hibernate.SessionFactory;
import org.hibernate.engine.jdbc.connections.spi.ConnectionProvider;
import tools.HibernateUtil;
import view.SerbaGuna;

/**
 *
 * @author Lenovo
 */
public class HrView extends javax.swing.JFrame {

    private final SessionFactory sf;
    private SerbaGuna sg;

    /**
     * Creates new form HRView
     */
    public HrView() {
        initComponents();
        this.sf = HibernateUtil.getSessionFactory();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        dpUtamaHr = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmRegion = new javax.swing.JMenu();
        jmOrganization = new javax.swing.JMenuItem();
        jmNetworking = new javax.swing.JMenuItem();
        jmAchievement = new javax.swing.JMenuItem();
        jmTraining = new javax.swing.JMenuItem();
        jmWorkingExperience = new javax.swing.JMenuItem();
        jmBahasaAsing = new javax.swing.JMenuItem();
        jmEducation = new javax.swing.JMenuItem();
        jmOperatingSystem = new javax.swing.JMenuItem();
        jmProgramming = new javax.swing.JMenuItem();
        jmTools = new javax.swing.JMenuItem();
        jmPersonalData = new javax.swing.JMenuItem();
        jmCountryId = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mniReportTabel = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HR VIEW .ORM");

        javax.swing.GroupLayout dpUtamaHrLayout = new javax.swing.GroupLayout(dpUtamaHr);
        dpUtamaHr.setLayout(dpUtamaHrLayout);
        dpUtamaHrLayout.setHorizontalGroup(
            dpUtamaHrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 629, Short.MAX_VALUE)
        );
        dpUtamaHrLayout.setVerticalGroup(
            dpUtamaHrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 465, Short.MAX_VALUE)
        );

        jmRegion.setText("File");

        jmOrganization.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        jmOrganization.setText("Organization");
        jmOrganization.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmOrganizationActionPerformed(evt);
            }
        });
        jmRegion.add(jmOrganization);

        jmNetworking.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jmNetworking.setText("Networking");
        jmNetworking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmNetworkingActionPerformed(evt);
            }
        });
        jmRegion.add(jmNetworking);

        jmAchievement.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jmAchievement.setText("Achievement");
        jmAchievement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmAchievementActionPerformed(evt);
            }
        });
        jmRegion.add(jmAchievement);

        jmTraining.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        jmTraining.setText("Training");
        jmTraining.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmTrainingActionPerformed(evt);
            }
        });
        jmRegion.add(jmTraining);

        jmWorkingExperience.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.CTRL_MASK));
        jmWorkingExperience.setText("Pengalaman Kerja");
        jmWorkingExperience.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmWorkingExperienceActionPerformed(evt);
            }
        });
        jmRegion.add(jmWorkingExperience);

        jmBahasaAsing.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        jmBahasaAsing.setText("Bahasa Asing");
        jmBahasaAsing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmBahasaAsingActionPerformed(evt);
            }
        });
        jmRegion.add(jmBahasaAsing);

        jmEducation.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        jmEducation.setText("Education");
        jmEducation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmEducationActionPerformed(evt);
            }
        });
        jmRegion.add(jmEducation);

        jmOperatingSystem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jmOperatingSystem.setText("Operating System");
        jmOperatingSystem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmOperatingSystemActionPerformed(evt);
            }
        });
        jmRegion.add(jmOperatingSystem);

        jmProgramming.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jmProgramming.setText("Programming");
        jmProgramming.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmProgrammingActionPerformed(evt);
            }
        });
        jmRegion.add(jmProgramming);

        jmTools.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        jmTools.setText("Tools");
        jmTools.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmToolsActionPerformed(evt);
            }
        });
        jmRegion.add(jmTools);

        jmPersonalData.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        jmPersonalData.setText("Personal Data");
        jmRegion.add(jmPersonalData);

        jmCountryId.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jmCountryId.setText("Country Id");
        jmCountryId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCountryIdActionPerformed(evt);
            }
        });
        jmRegion.add(jmCountryId);

        jMenuBar1.add(jmRegion);

        jMenu2.setText("Report");

        mniReportTabel.setText("Report Tabel");
        mniReportTabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniReportTabelActionPerformed(evt);
            }
        });
        jMenu2.add(mniReportTabel);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dpUtamaHr)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dpUtamaHr, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmOrganizationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmOrganizationActionPerformed
        // TODO add your handling code here:
        OrganizationView organizationView = new OrganizationView();
        organizationView.show();
        dpUtamaHr.add(organizationView);
    }//GEN-LAST:event_jmOrganizationActionPerformed

    private void jmNetworkingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmNetworkingActionPerformed
        // TODO add your handling code here:
        CountryView countryView = new CountryView(sf);
        countryView.show();
        dpUtamaHr.add(countryView);
    }//GEN-LAST:event_jmNetworkingActionPerformed

    private void jmAchievementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmAchievementActionPerformed
        // TODO add your handling code here:
        AchievementView achievementView = new AchievementView();
        achievementView.show();
        dpUtamaHr.add(achievementView);
    }//GEN-LAST:event_jmAchievementActionPerformed

    private void jmTrainingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmTrainingActionPerformed
        // TODO add your handling code here:
        TrainingView trainingView = new TrainingView();
        trainingView.show();
        dpUtamaHr.add(trainingView);
    }//GEN-LAST:event_jmTrainingActionPerformed

    private void jmWorkingExperienceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmWorkingExperienceActionPerformed
         // TODO add your handling code here:
        PengalamanKerjaView pengalamanKerjaView = new PengalamanKerjaView();
        pengalamanKerjaView.show();
        dpUtamaHr.add(pengalamanKerjaView);
    }//GEN-LAST:event_jmWorkingExperienceActionPerformed

    private void jmBahasaAsingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmBahasaAsingActionPerformed
        // TODO add your handling code here:
        BahasaAsingView bahasaAsingView = new BahasaAsingView();
        bahasaAsingView.show();
        dpUtamaHr.add(bahasaAsingView);
    }//GEN-LAST:event_jmBahasaAsingActionPerformed

    private void mniReportTabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniReportTabelActionPerformed
        // TODO add your handling code here:
        String path = "E:\\E\\MII\\bootcamp\\GUI_HR_ORM\\build\\classes\\view\\report\\RegionReport.jrxml";

    }//GEN-LAST:event_mniReportTabelActionPerformed

    private void jmCountryIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCountryIdActionPerformed
        // TODO add your handling code here:
        CountryView countryView = new CountryView(sf);
        countryView.show();
        dpUtamaHr.add(countryView);
    }//GEN-LAST:event_jmCountryIdActionPerformed

    private void jmEducationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmEducationActionPerformed
         // TODO add your handling code here:
         EducationView educationView = new EducationView();
         educationView.show();
         dpUtamaHr.add(educationView);
    }//GEN-LAST:event_jmEducationActionPerformed

    private void jmOperatingSystemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmOperatingSystemActionPerformed
         // TODO add your handling code here:
         OperatingSystemView operatingSystemView = new OperatingSystemView();
         operatingSystemView.show();
         dpUtamaHr.add(operatingSystemView);
    }//GEN-LAST:event_jmOperatingSystemActionPerformed

    private void jmProgrammingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmProgrammingActionPerformed
         // TODO add your handling code here:
         ProgrammingView programmingView = new ProgrammingView();
         programmingView.show();
         dpUtamaHr.add(programmingView);
    }//GEN-LAST:event_jmProgrammingActionPerformed

    private void jmToolsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmToolsActionPerformed
         // TODO add your handling code here:
         ToolsView toolsView = new ToolsView();
         toolsView.show();
         dpUtamaHr.add(toolsView);
    }//GEN-LAST:event_jmToolsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HrView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HrView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HrView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HrView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HrView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane dpUtamaHr;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jmAchievement;
    private javax.swing.JMenuItem jmBahasaAsing;
    private javax.swing.JMenuItem jmCountryId;
    private javax.swing.JMenuItem jmEducation;
    private javax.swing.JMenuItem jmNetworking;
    private javax.swing.JMenuItem jmOperatingSystem;
    private javax.swing.JMenuItem jmOrganization;
    private javax.swing.JMenuItem jmPersonalData;
    private javax.swing.JMenuItem jmProgramming;
    private javax.swing.JMenu jmRegion;
    private javax.swing.JMenuItem jmTools;
    private javax.swing.JMenuItem jmTraining;
    private javax.swing.JMenuItem jmWorkingExperience;
    private javax.swing.JMenuItem mniReportTabel;
    // End of variables declaration//GEN-END:variables
}
