
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.BorderLayout;
import java.io.File;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JInternalFrame;
//import net.sf.jasperreports.engine.JasperCompileManager;
//import net.sf.jasperreports.engine.JasperFillManager;
//import net.sf.jasperreports.engine.JasperPrint;
//import net.sf.jasperreports.engine.JasperReport;
//import net.sf.jasperreports.engine.design.JasperDesign;
//import net.sf.jasperreports.engine.xml.JRXmlLoader;
//import net.sf.jasperreports.view.JRViewer;
import org.hibernate.SessionFactory;
import org.hibernate.engine.jdbc.connections.spi.ConnectionProvider;
import report.ReportView;
import tools.HibernateUtil;
import view.SerbaGuna;

/**
 *
 * @author Lenovo
 */
public class HrView extends javax.swing.JFrame {

    private final SessionFactory sf;
    private SerbaGuna sg;

    /**
     * Creates new form HRView
     */
    public HrView(boolean a, String nama) {
        if (a) {
            initComponents();
        }
        this.sf = HibernateUtil.getSessionFactory();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        dpUtamaHr = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmRegion = new javax.swing.JMenu();
        jmOrganization = new javax.swing.JMenuItem();
        jmNetworking = new javax.swing.JMenuItem();
        jmAchievement = new javax.swing.JMenuItem();
        jmTraining = new javax.swing.JMenuItem();
        jmWorkingExperience = new javax.swing.JMenuItem();
        jmBahasaAsing = new javax.swing.JMenuItem();
        jmEducation = new javax.swing.JMenuItem();
        jmOperatingSystem = new javax.swing.JMenuItem();
        jmProgramming = new javax.swing.JMenuItem();
        jmTools = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        MiLoginView = new javax.swing.JMenuItem();
        MiInsertForm1 = new javax.swing.JMenuItem();
        MiInsertForm2 = new javax.swing.JMenuItem();
        MiUpdatePassword = new javax.swing.JMenuItem();
        MiLogOut = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mniReportTabelTools = new javax.swing.JMenuItem();
        OsReport = new javax.swing.JMenuItem();
        BahasaReport = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        viewKandidat = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        jMenu1.setText("jMenu1");

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HR VIEW .ORM");

        javax.swing.GroupLayout dpUtamaHrLayout = new javax.swing.GroupLayout(dpUtamaHr);
        dpUtamaHr.setLayout(dpUtamaHrLayout);
        dpUtamaHrLayout.setHorizontalGroup(
            dpUtamaHrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 629, Short.MAX_VALUE)
        );
        dpUtamaHrLayout.setVerticalGroup(
            dpUtamaHrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 465, Short.MAX_VALUE)
        );

        jmRegion.setText("File");

        jmOrganization.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        jmOrganization.setText("Organization");
        jmOrganization.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmOrganizationActionPerformed(evt);
            }
        });
        jmRegion.add(jmOrganization);

        jmNetworking.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jmNetworking.setText("Networking");
        jmNetworking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmNetworkingActionPerformed(evt);
            }
        });
        jmRegion.add(jmNetworking);

        jmAchievement.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jmAchievement.setText("Achievement");
        jmAchievement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmAchievementActionPerformed(evt);
            }
        });
        jmRegion.add(jmAchievement);

        jmTraining.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        jmTraining.setText("Training");
        jmTraining.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmTrainingActionPerformed(evt);
            }
        });
        jmRegion.add(jmTraining);

        jmWorkingExperience.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.CTRL_MASK));
        jmWorkingExperience.setText("Experience Working");
        jmWorkingExperience.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmWorkingExperienceActionPerformed(evt);
            }
        });
        jmRegion.add(jmWorkingExperience);

        jmBahasaAsing.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        jmBahasaAsing.setText("Language");
        jmBahasaAsing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmBahasaAsingActionPerformed(evt);
            }
        });
        jmRegion.add(jmBahasaAsing);

        jmEducation.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        jmEducation.setText("Education");
        jmEducation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmEducationActionPerformed(evt);
            }
        });
        jmRegion.add(jmEducation);

        jmOperatingSystem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jmOperatingSystem.setText("Operating System");
        jmOperatingSystem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmOperatingSystemActionPerformed(evt);
            }
        });
        jmRegion.add(jmOperatingSystem);

        jmProgramming.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jmProgramming.setText("Programming");
        jmProgramming.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmProgrammingActionPerformed(evt);
            }
        });
        jmRegion.add(jmProgramming);

        jmTools.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        jmTools.setText("Tools");
        jmTools.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmToolsActionPerformed(evt);
            }
        });
        jmRegion.add(jmTools);

        jMenu5.setText("Main Page");

        MiLoginView.setText("Login View");
        MiLoginView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MiLoginViewActionPerformed(evt);
            }
        });
        jMenu5.add(MiLoginView);

        MiInsertForm1.setText("Insert Form 1");
        MiInsertForm1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MiInsertForm1ActionPerformed(evt);
            }
        });
        jMenu5.add(MiInsertForm1);

        MiInsertForm2.setText("Insert form 2");
        MiInsertForm2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MiInsertForm2ActionPerformed(evt);
            }
        });
        jMenu5.add(MiInsertForm2);

        MiUpdatePassword.setText("Update Password");
        MiUpdatePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MiUpdatePasswordActionPerformed(evt);
            }
        });
        jMenu5.add(MiUpdatePassword);

        MiLogOut.setText("Log Out");
        MiLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MiLogOutActionPerformed(evt);
            }
        });
        jMenu5.add(MiLogOut);

        jmRegion.add(jMenu5);

        jMenuBar1.add(jmRegion);

        jMenu2.setText("Report");

        mniReportTabelTools.setText("Tools Report");
        mniReportTabelTools.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniReportTabelToolsActionPerformed(evt);
            }
        });
        jMenu2.add(mniReportTabelTools);

        OsReport.setText("OS Report");
        OsReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OsReportActionPerformed(evt);
            }
        });
        jMenu2.add(OsReport);

        BahasaReport.setText("Language Report");
        BahasaReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BahasaReportActionPerformed(evt);
            }
        });
        jMenu2.add(BahasaReport);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("View");

        jMenuItem1.setText("cv kandidat");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem1);

        viewKandidat.setText("menuKandidatView");
        viewKandidat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewKandidatActionPerformed(evt);
            }
        });
        jMenu4.add(viewKandidat);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dpUtamaHr)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dpUtamaHr, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmOrganizationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmOrganizationActionPerformed
        // TODO add your handling code here:
        OrganizationView organizationView = new OrganizationView(sf);
        organizationView.show();
        dpUtamaHr.add(organizationView);
    }//GEN-LAST:event_jmOrganizationActionPerformed

    private void jmNetworkingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmNetworkingActionPerformed
        // TODO add your handling code here:
        NetworkingView networkingView = new NetworkingView(sf);
        networkingView.show();
        dpUtamaHr.add(networkingView);
    }//GEN-LAST:event_jmNetworkingActionPerformed

    private void jmAchievementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmAchievementActionPerformed
        // TODO add your handling code here:
        AchievementView achievementView = new AchievementView(sf);
        achievementView.show();
        dpUtamaHr.add(achievementView);
    }//GEN-LAST:event_jmAchievementActionPerformed

    private void jmTrainingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmTrainingActionPerformed
        // TODO add your handling code here:
        TrainingView trainingView = new TrainingView(sf);
        trainingView.show();
        dpUtamaHr.add(trainingView);
    }//GEN-LAST:event_jmTrainingActionPerformed

    private void jmWorkingExperienceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmWorkingExperienceActionPerformed
        // TODO add your handling code here:
        PengalamanKerjaView pengalamanKerjaView = new PengalamanKerjaView(sf);
        pengalamanKerjaView.show();
        dpUtamaHr.add(pengalamanKerjaView);
    }//GEN-LAST:event_jmWorkingExperienceActionPerformed

    private void jmBahasaAsingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmBahasaAsingActionPerformed
        // TODO add your handling code here:
        BahasaAsingView bahasaAsingView = new BahasaAsingView(sf);
        bahasaAsingView.show();
        dpUtamaHr.add(bahasaAsingView);
    }//GEN-LAST:event_jmBahasaAsingActionPerformed

    private void mniReportTabelToolsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniReportTabelToolsActionPerformed
        // TODO add your handling code here:
        this.showReport("ToolsReport.jrxml");
    }//GEN-LAST:event_mniReportTabelToolsActionPerformed

    private void jmEducationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmEducationActionPerformed
        // TODO add your handling code here:
        EducationView educationView = new EducationView(sf);
        educationView.show();
        dpUtamaHr.add(educationView);
    }//GEN-LAST:event_jmEducationActionPerformed

    private void jmOperatingSystemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmOperatingSystemActionPerformed
        // TODO add your handling code here:
        OperatingSystemView operatingSystemView = new OperatingSystemView(sf);
        operatingSystemView.show();
        dpUtamaHr.add(operatingSystemView);
    }//GEN-LAST:event_jmOperatingSystemActionPerformed

    private void jmProgrammingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmProgrammingActionPerformed
        // TODO add your handling code here:
        ProgrammingView programmingView = new ProgrammingView(sf);
        programmingView.show();
        dpUtamaHr.add(programmingView);
    }//GEN-LAST:event_jmProgrammingActionPerformed

    private void jmToolsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmToolsActionPerformed
        // TODO add your handling code here:
        ToolsView toolsView = new ToolsView(sf);
        toolsView.show();
        dpUtamaHr.add(toolsView);
    }//GEN-LAST:event_jmToolsActionPerformed

    private void OsReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OsReportActionPerformed
        // TODO add your handling code here:
        this.showReport("OSReport.jrxml");
    }//GEN-LAST:event_OsReportActionPerformed

    private void BahasaReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BahasaReportActionPerformed
        // TODO add your handling code here:
        this.showReport("BahasaReport.jrxml");
    }//GEN-LAST:event_BahasaReportActionPerformed

    private void viewKandidatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewKandidatActionPerformed
        // TODO add your handling code here:
        try {
            KandidatView kandidatView = new KandidatView(sf);
            kandidatView.show();
            dpUtamaHr.add(kandidatView);
        } catch (SQLException ex) {
            Logger.getLogger(HrView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_viewKandidatActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        cv_kandidat cv = new cv_kandidat();
        cv.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void MiLoginViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MiLoginViewActionPerformed
        // TODO add your handling code here:
        LoginView login = new LoginView(sf);
        login.setVisible(true);
        dpUtamaHr.add(login);
    }//GEN-LAST:event_MiLoginViewActionPerformed

    private void MiInsertForm1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MiInsertForm1ActionPerformed
        // TODO add your handling code here:
        PersonalDataView1 personalDataView1 = new PersonalDataView1(sf);
            personalDataView1.setVisible(true);
            dpUtamaHr.add(personalDataView1);
    }//GEN-LAST:event_MiInsertForm1ActionPerformed

    private void MiInsertForm2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MiInsertForm2ActionPerformed
        // TODO add your handling code here:
        PersonalDataView2 personalDataView2 = new PersonalDataView2(sf);
            personalDataView2.setVisible(true);
            dpUtamaHr.add(personalDataView2);
    }//GEN-LAST:event_MiInsertForm2ActionPerformed

    private void MiUpdatePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MiUpdatePasswordActionPerformed
        // TODO add your handling code here:
        LoginKandidatView loginKandidatView = new LoginKandidatView(sf);
            loginKandidatView.setVisible(true);
            dpUtamaHr.add(loginKandidatView);
    }//GEN-LAST:event_MiUpdatePasswordActionPerformed

    private void MiLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MiLogOutActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_MiLogOutActionPerformed

    private void showReport(String path) {
        ReportView reportView = new ReportView(sf, "src\\report\\" + path + "");
        reportView.show();
        dpUtamaHr.add(reportView);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HrView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HrView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HrView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HrView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HrView(true, "").setVisible(false);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem BahasaReport;
    private javax.swing.JMenuItem MiInsertForm1;
    private javax.swing.JMenuItem MiInsertForm2;
    private javax.swing.JMenuItem MiLogOut;
    private javax.swing.JMenuItem MiLoginView;
    private javax.swing.JMenuItem MiUpdatePassword;
    private javax.swing.JMenuItem OsReport;
    private javax.swing.JDesktopPane dpUtamaHr;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jmAchievement;
    private javax.swing.JMenuItem jmBahasaAsing;
    private javax.swing.JMenuItem jmEducation;
    private javax.swing.JMenuItem jmNetworking;
    private javax.swing.JMenuItem jmOperatingSystem;
    private javax.swing.JMenuItem jmOrganization;
    private javax.swing.JMenuItem jmProgramming;
    private javax.swing.JMenu jmRegion;
    private javax.swing.JMenuItem jmTools;
    private javax.swing.JMenuItem jmTraining;
    private javax.swing.JMenuItem jmWorkingExperience;
    private javax.swing.JMenuItem mniReportTabelTools;
    private javax.swing.JMenuItem viewKandidat;
    // End of variables declaration//GEN-END:variables
}
