/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.PersonalController;
import java.sql.SQLException;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import org.hibernate.Hibernate;
import org.hibernate.SessionFactory;
import tools.HibernateUtil;

/**
 *
 * @author X453MA
 */
public class KandidatView extends javax.swing.JInternalFrame {

    /**
     * Creates new form KandidatView
     */
    PersonalController pc;
    
    public KandidatView(SessionFactory sf) throws SQLException {
        initComponents();
        pc = new PersonalController(sf);
        bindingStatusWaiting(pc.getStatusWaiting());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblKandidat = new javax.swing.JTable();

        setClosable(true);
        setTitle("Kandidat");

        tblKandidat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblKandidat);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(179, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void bindingStatusWaiting(List<Object> object) {
        String[] header = {"No.", "ID Personal", "Nama", "Status"};
        String[][] data = new String[object.size()][header.length];
        for (int i = 0; i < (int)object.get(3); i++) {
            data[i][1] = object.get(0) + "";
            data[i][2] = object.get(1) + "";
            data[i][3] = object.get(2) + "";
        }
        tblKandidat.setModel(new DefaultTableModel(data, header));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblKandidat;
    // End of variables declaration//GEN-END:variables
}
