/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.GetIdController;
import controller.PersonalController;
import java.math.BigDecimal;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import org.hibernate.SessionFactory;
import view.SerbaGuna.pesan;
import model.*;

/**
 *
 * @author Lenovo
 */
public class PersonalDataView2 extends javax.swing.JInternalFrame {
    private final PersonalController controller;
     private GetIdController controller1;
    private final SerbaGuna sg;
    /**
     * Creates new form PersonalDataView
     * @param factory
     */
    public PersonalDataView2(SessionFactory factory) {
        initComponents();
        controller = new PersonalController(factory);
        controller1 = new GetIdController(factory);
        controller.loadCmbTools(cmbTools, "tool");
        controller.loadCmbTools(cmbNamaOS, "os");
        controller.loadCmbTools(cmbBhsaProg, "bhsProg");
        controller.loadCmbTools(cmbEduLevel, "edul");
        controller.loadCmbTools(cmbEventPenghargaan, "eventPh");
        controller.loadCmbTools(cmbInstansi, "insta");
        controller.loadCmbTools(cmbNetworking, "network");
        controller.loadCmbTools(cmbNamaPenghaargaan, "nmPenghargaan");
        controller.loadCmbTools(cmbEventPenghargaan, "evPenghargaan");
        controller.loadCmbTools(cmbNameTrain, "nmTrain");
        controller.loadCmbTools(cmbLembgTraining, "lgTrain");
        sg = new SerbaGuna();
        txtIdPersonal.setText(controller.getAutoId().toString());txtIdPersonal.setEnabled(true);
        reset();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSave = new javax.swing.JButton();
        btnViewData = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        cmbInstansi = new javax.swing.JComboBox<>();
        cmbEduLevel = new javax.swing.JComboBox<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtInstansi = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtEduLevel = new javax.swing.JTextArea();
        jScrollPane7 = new javax.swing.JScrollPane();
        txtMajor = new javax.swing.JTextArea();
        txtGPA = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        cmbNamaPenghaargaan = new javax.swing.JComboBox<>();
        cmbEventPenghargaan = new javax.swing.JComboBox<>();
        txtTahunAchiv = new javax.swing.JTextField();
        cmbNameTrain = new javax.swing.JComboBox<>();
        cmbLembgTraining = new javax.swing.JComboBox<>();
        jXDatePicker5 = new org.jdesktop.swingx.JXDatePicker();
        jXDatePicker6 = new org.jdesktop.swingx.JXDatePicker();
        jScrollPane10 = new javax.swing.JScrollPane();
        txtNamaPerhar = new javax.swing.JTextArea();
        jScrollPane9 = new javax.swing.JScrollPane();
        txtEventPenghar = new javax.swing.JTextArea();
        jScrollPane8 = new javax.swing.JScrollPane();
        txtNamaTrain = new javax.swing.JTextArea();
        jScrollPane11 = new javax.swing.JScrollPane();
        txtLbgTrain = new javax.swing.JTextArea();
        jLabel32 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        cmbBhsaProg = new javax.swing.JComboBox<>();
        cmbNetworking = new javax.swing.JComboBox<>();
        cmbTools = new javax.swing.JComboBox<>();
        cmbNamaOS = new javax.swing.JComboBox<>();
        jScrollPane12 = new javax.swing.JScrollPane();
        txtBhsaProg = new javax.swing.JTextArea();
        jScrollPane13 = new javax.swing.JScrollPane();
        txtNetworking = new javax.swing.JTextArea();
        jLabel48 = new javax.swing.JLabel();
        txtYearIn = new javax.swing.JTextField();
        txtGraduation = new javax.swing.JTextField();
        btnReset = new javax.swing.JButton();
        txtIdPersonal = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Form Personal Data Kandidat");

        btnSave.setText("SAVE");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnViewData.setText("VIEW");
        btnViewData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDataActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Educational Qualification", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Tahoma", 1, 10))); // NOI18N

        jLabel10.setText("Instansi");

        jLabel11.setText("Education Level");

        jLabel12.setText(" Major");

        jLabel13.setText("GPA");

        jLabel14.setText("Year In");

        jLabel15.setText("Graduation");

        cmbInstansi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cmbInstansiMouseEntered(evt);
            }
        });

        cmbEduLevel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cmbEduLevelMouseEntered(evt);
            }
        });

        txtInstansi.setColumns(20);
        txtInstansi.setRows(5);
        jScrollPane5.setViewportView(txtInstansi);

        txtEduLevel.setColumns(20);
        txtEduLevel.setRows(5);
        jScrollPane6.setViewportView(txtEduLevel);

        txtMajor.setColumns(20);
        txtMajor.setRows(5);
        jScrollPane7.setViewportView(txtMajor);

        jLabel28.setText("Nama Penghargaan");

        jLabel29.setText("Event Penghargaan");

        jLabel30.setText("Tahun");

        jLabel31.setText("Nama Training");

        jLabel41.setText("Lembaga Training");

        jLabel42.setText("Tanggal Mulai");

        jLabel43.setText("Tanggal Selesai");

        cmbNamaPenghaargaan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cmbNamaPenghaargaanMouseEntered(evt);
            }
        });

        cmbEventPenghargaan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cmbEventPenghargaanMouseEntered(evt);
            }
        });

        cmbNameTrain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cmbNameTrainMouseEntered(evt);
            }
        });

        cmbLembgTraining.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cmbLembgTrainingMouseEntered(evt);
            }
        });

        txtNamaPerhar.setColumns(20);
        txtNamaPerhar.setRows(5);
        jScrollPane10.setViewportView(txtNamaPerhar);

        txtEventPenghar.setColumns(20);
        txtEventPenghar.setRows(5);
        jScrollPane9.setViewportView(txtEventPenghar);

        txtNamaTrain.setColumns(20);
        txtNamaTrain.setRows(5);
        jScrollPane8.setViewportView(txtNamaTrain);

        txtLbgTrain.setColumns(20);
        txtLbgTrain.setRows(5);
        jScrollPane11.setViewportView(txtLbgTrain);

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel32.setText("Achievement & Training");

        jLabel44.setText("Language Programming");

        jLabel45.setText("Networking");

        jLabel46.setText("Tools");

        jLabel47.setText("Nama OS");

        cmbBhsaProg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cmbBhsaProgMouseEntered(evt);
            }
        });

        cmbNetworking.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cmbNetworkingMouseEntered(evt);
            }
        });

        txtBhsaProg.setColumns(20);
        txtBhsaProg.setRows(5);
        jScrollPane12.setViewportView(txtBhsaProg);

        txtNetworking.setColumns(20);
        txtNetworking.setRows(5);
        jScrollPane13.setViewportView(txtNetworking);

        jLabel48.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel48.setText("IT Skill");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(37, 37, 37))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel13))
                                .addGap(22, 22, 22))
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cmbInstansi, 0, 207, Short.MAX_VALUE)
                                .addComponent(cmbEduLevel, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtYearIn)
                                .addComponent(txtGPA)
                                .addComponent(txtGraduation, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel31)
                            .addComponent(jLabel41)
                            .addComponent(jLabel42)
                            .addComponent(jLabel43)
                            .addComponent(jLabel28)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel30, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel29, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jLabel48)
                            .addComponent(jLabel47)
                            .addComponent(jLabel44)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel46, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel45, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(cmbTools, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cmbNetworking, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cmbBhsaProg, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jXDatePicker6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                                .addComponent(jXDatePicker5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cmbLembgTraining, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cmbNameTrain, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cmbEventPenghargaan, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cmbNamaPenghaargaan, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtTahunAchiv))
                            .addComponent(cmbNamaOS, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel32))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 845, Short.MAX_VALUE)
                        .addComponent(jScrollPane5))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane11)
                        .addComponent(jScrollPane13)
                        .addComponent(jScrollPane9)
                        .addComponent(jScrollPane10, javax.swing.GroupLayout.DEFAULT_SIZE, 842, Short.MAX_VALUE)
                        .addComponent(jScrollPane8)
                        .addComponent(jScrollPane12)
                        .addComponent(jScrollPane7))
                    .addComponent(jLabel12))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(cmbInstansi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbEduLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jLabel13)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15)
                                .addComponent(jLabel15))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(txtGPA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtYearIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)
                                .addComponent(txtGraduation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(jLabel12)
                        .addGap(3, 3, 3)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel28)
                            .addComponent(cmbNamaPenghaargaan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel29)
                            .addComponent(cmbEventPenghargaan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel30)
                            .addComponent(txtTahunAchiv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel31)
                            .addComponent(cmbNameTrain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel41)
                            .addComponent(cmbLembgTraining, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel42)
                            .addComponent(jXDatePicker5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel43)
                            .addComponent(jXDatePicker6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel48)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane12, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel44)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel45)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel46)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel47))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(cmbBhsaProg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbNetworking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbTools, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, 0)
                        .addComponent(cmbNamaOS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        btnReset.setText("RESET");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        txtIdPersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdPersonalActionPerformed(evt);
            }
        });

        jLabel16.setText("ID CV Anda");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnReset, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnViewData))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtIdPersonal, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnSave, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtIdPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnViewData)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnReset))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnViewDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnViewDataActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        String idPer = controller1.getLastId3().toString();
        String idEduT = controller1.getAutoId4().toString();String idedu = controller1.getLastId4().toString(); 
        String idAchiT = controller1.getAutoId5().toString();String idAchi = controller1.getLastId5().toString(); 
        //controller.saveOrUpdate3(txtInstansi.getText(), txtEduLevel.getText(), idEduT, "w", txtGPA.getText(), txtYearIn.getText(), txtGraduation.getText(), txtMajor.getText(), idedu, idPer);
        //(String namaachievement, String nameevant, BigInteger year, BigDecimal idachdetail, String status, Achievement idachievement, Personaldata idpersonal)
       controller.saveOrUpdate4(txtNamaPerhar.getText(), txtEventPenghar.getText(), txtTahunAchiv.getText(), idAchiT, "w", idAchi, idPer);
        if(!txtIdPersonal.isEnabled()){
            JOptionPane.showMessageDialog(this, pesan.update.getPesan(), "Update", JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            JOptionPane.showMessageDialog(this, pesan.save.getPesan(), "Save", JOptionPane.INFORMATION_MESSAGE);
        }
        reset();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtIdPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdPersonalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdPersonalActionPerformed

    private void cmbInstansiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbInstansiMouseEntered
        // TODO add your handling code here:
        txtInstansi.setText(cmbInstansi.getSelectedItem()+"");
    }//GEN-LAST:event_cmbInstansiMouseEntered

    private void cmbEduLevelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbEduLevelMouseEntered
        // TODO add your handling code here:
        txtEduLevel.setText(cmbEduLevel.getSelectedItem()+"");
    }//GEN-LAST:event_cmbEduLevelMouseEntered

    private void cmbNamaPenghaargaanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbNamaPenghaargaanMouseEntered
        // TODO add your handling code here:
        txtNamaPerhar.setText(cmbNamaPenghaargaan.getSelectedItem()+"");
    }//GEN-LAST:event_cmbNamaPenghaargaanMouseEntered

    private void cmbEventPenghargaanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbEventPenghargaanMouseEntered
        // TODO add your handling code here:
        txtEventPenghar.setText(cmbEventPenghargaan.getSelectedItem()+"");
    }//GEN-LAST:event_cmbEventPenghargaanMouseEntered

    private void cmbNameTrainMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbNameTrainMouseEntered
        // TODO add your handling code here:
        txtNamaTrain.setText(cmbNameTrain.getSelectedItem()+"");
    }//GEN-LAST:event_cmbNameTrainMouseEntered

    private void cmbLembgTrainingMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbLembgTrainingMouseEntered
        // TODO add your handling code here:
        txtLbgTrain.setText(cmbLembgTraining.getSelectedItem()+"");
    }//GEN-LAST:event_cmbLembgTrainingMouseEntered

    private void cmbBhsaProgMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbBhsaProgMouseEntered
        // TODO add your handling code here:
        txtBhsaProg.setText(cmbBhsaProg.getSelectedItem()+"");
    }//GEN-LAST:event_cmbBhsaProgMouseEntered

    private void cmbNetworkingMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbNetworkingMouseEntered
        // TODO add your handling code here:
        txtNetworking.setText(cmbNetworking.getSelectedItem()+"");
    }//GEN-LAST:event_cmbNetworkingMouseEntered


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnViewData;
    private javax.swing.JComboBox<String> cmbBhsaProg;
    private javax.swing.JComboBox<String> cmbEduLevel;
    private javax.swing.JComboBox<String> cmbEventPenghargaan;
    private javax.swing.JComboBox<String> cmbInstansi;
    private javax.swing.JComboBox<String> cmbLembgTraining;
    private javax.swing.JComboBox<String> cmbNamaOS;
    private javax.swing.JComboBox<String> cmbNamaPenghaargaan;
    private javax.swing.JComboBox<String> cmbNameTrain;
    private javax.swing.JComboBox<String> cmbNetworking;
    private javax.swing.JComboBox<String> cmbTools;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker5;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker6;
    private javax.swing.JTextArea txtBhsaProg;
    private javax.swing.JTextArea txtEduLevel;
    private javax.swing.JTextArea txtEventPenghar;
    private javax.swing.JTextField txtGPA;
    private javax.swing.JTextField txtGraduation;
    private javax.swing.JTextField txtIdPersonal;
    private javax.swing.JTextArea txtInstansi;
    private javax.swing.JTextArea txtLbgTrain;
    private javax.swing.JTextArea txtMajor;
    private javax.swing.JTextArea txtNamaPerhar;
    private javax.swing.JTextArea txtNamaTrain;
    private javax.swing.JTextArea txtNetworking;
    private javax.swing.JTextField txtTahunAchiv;
    private javax.swing.JTextField txtYearIn;
    // End of variables declaration//GEN-END:variables

    public  void reset(){
        txtIdPersonal.setText(controller.getAutoId().toString());txtIdPersonal.setEnabled(true);
        txtEduLevel.setText("Jenjang Pendidikan");
        txtEventPenghar.setText("Event Pengahargaan");
        txtInstansi.setText("Nama Instansi/Kampus/Sekolahan");
        txtBhsaProg.setText("Kompetensi Bahasa Pemrograman");
        txtGPA.setText("4.00");
        txtLbgTrain.setText("Nama Lembaga Training");
        txtMajor.setText("Jurusan");
        txtNamaPerhar.setText("Nama Penghargaan");
        txtNamaTrain.setText("Nama Training");
        txtNetworking.setText("Kompetensi Networking");
        txtTahunAchiv.setText("");
        txtYearIn.setText("");
        txtGraduation.setText("");
    }
}
