/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.*;
import view.*;
import controller.PersonalController;
import java.math.BigDecimal;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import org.hibernate.SessionFactory;
import view.SerbaGuna.pesan;
import view.*;
import model.*;
import tools.HibernateUtil;

/**
 *
 * @author Lenovo
 */
public class PersonalDataView1 extends javax.swing.JInternalFrame {
    private final PersonalController controller;
   private GetIdController controller1;
   private SessionFactory factory;
    private final SerbaGuna sg;
    /**
     * Creates new form PersonalDataView
     * @param factory
     */
    public PersonalDataView1(SessionFactory factory) {
        initComponents();
        this.factory = HibernateUtil.getSessionFactory();
        controller = new PersonalController(factory);
        controller1 = new GetIdController(factory);
        controller.loadCmbTools(cmbBahasa, "bahasa1");
        controller.loadCmbTools(cmbJabatan, "jbatn");
        controller.loadCmbTools(cmbNamaOraginsasi, "naOr");
        controller.loadCmbTools(cmbNmPerusahaan, "namaPr");
        controller.loadCmbTools(cmbJabatanPeru, "city");
        controller.loadCmbTools(cmbStatusKwn, "kawin");
        sg = new SerbaGuna();
        txtIdPersonal.setText(controller.getAutoId().toString());txtIdPersonal.setEnabled(true);
        reset();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dpPersonal = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtStatus = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        txtMail = new javax.swing.JTextField();
        txtPhoto = new javax.swing.JTextField();
        cmbBahasa = new javax.swing.JComboBox<>();
        cmbNegara = new javax.swing.JComboBox<>();
        cmbSex = new javax.swing.JComboBox<>();
        dateBirth = new org.jdesktop.swingx.JXDatePicker();
        btnPhoto = new javax.swing.JButton();
        cmbMail = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        cmbNamaOraginsasi = new javax.swing.JComboBox<>();
        cmbJabatan = new javax.swing.JComboBox<>();
        dateOrgAw = new org.jdesktop.swingx.JXDatePicker();
        dateOrgAk = new org.jdesktop.swingx.JXDatePicker();
        cmbNmPerusahaan = new javax.swing.JComboBox<>();
        cmbJabatanPeru = new javax.swing.JComboBox<>();
        DateAwKer = new org.jdesktop.swingx.JXDatePicker();
        DateAkKer = new org.jdesktop.swingx.JXDatePicker();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtNamaOrga = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtJabatanOrg = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtNamaPerus = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtJabatanPrus = new javax.swing.JTextArea();
        jLabel24 = new javax.swing.JLabel();
        txtbahsa = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        cmbStatusKwn = new javax.swing.JComboBox<>();
        btnSave = new javax.swing.JButton();
        btnViewData = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        txtIdPersonal = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Form Personal Data Kandidat");

        dpPersonal.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Personal Data", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jLabel1.setText("Name");

        jLabel2.setText("Date of Birth");

        jLabel3.setText("Nationality");

        jLabel4.setText("Marital Status");

        jLabel5.setText("Gender/Sex");

        jLabel6.setText("Phone Number");

        jLabel7.setText("Email");

        jLabel8.setText("Foreign Language");

        jLabel9.setText("Photo (Max 500 KB)");

        cmbBahasa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cmbBahasaMouseEntered(evt);
            }
        });

        cmbNegara.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "WNI", "WNA" }));

        cmbSex.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laki-Laki", "Perempuan" }));

        btnPhoto.setText("Chose Photo");

        cmbMail.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "@gmail.com", "@yahoo.com", "@yahoo.co.id", "@mii.co.id" }));
        cmbMail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cmbMailMouseEntered(evt);
            }
        });

        jLabel16.setText("Nama Organisasi");

        jLabel17.setText("Jabatan di Organisasi");

        jLabel18.setText("Bulan & Tahun Mulai");

        jLabel19.setText("Bulan & Tahun Selesai");

        jLabel20.setText("Nama Perusahaan");

        jLabel21.setText("Lokasi Perusahaan");

        jLabel22.setText("Bulan & Tahun Mulai");

        jLabel23.setText("Bulan & Tahun Selesai");

        cmbNamaOraginsasi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cmbNamaOraginsasiMouseEntered(evt);
            }
        });
        cmbNamaOraginsasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbNamaOraginsasiActionPerformed(evt);
            }
        });

        cmbJabatan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cmbJabatanMouseEntered(evt);
            }
        });

        cmbNmPerusahaan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cmbNmPerusahaanMouseEntered(evt);
            }
        });
        cmbNmPerusahaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbNmPerusahaanActionPerformed(evt);
            }
        });

        cmbJabatanPeru.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cmbJabatanPeruMouseEntered(evt);
            }
        });

        txtNamaOrga.setColumns(20);
        txtNamaOrga.setRows(5);
        jScrollPane3.setViewportView(txtNamaOrga);

        txtJabatanOrg.setColumns(20);
        txtJabatanOrg.setRows(5);
        jScrollPane1.setViewportView(txtJabatanOrg);

        txtNamaPerus.setColumns(20);
        txtNamaPerus.setRows(5);
        jScrollPane2.setViewportView(txtNamaPerus);

        txtJabatanPrus.setColumns(20);
        txtJabatanPrus.setRows(5);
        jScrollPane4.setViewportView(txtJabatanPrus);

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel24.setText("Organication Experience");

        txtbahsa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtbahsaKeyTyped(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel25.setText("Working Experience");

        cmbStatusKwn.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kawin", "Lajang", "Duda", "Janda" }));
        cmbStatusKwn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cmbStatusKwnMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout dpPersonalLayout = new javax.swing.GroupLayout(dpPersonal);
        dpPersonal.setLayout(dpPersonalLayout);
        dpPersonalLayout.setHorizontalGroup(
            dpPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dpPersonalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dpPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dpPersonalLayout.createSequentialGroup()
                        .addGroup(dpPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(jLabel20)
                            .addComponent(jLabel22)
                            .addComponent(jLabel23))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(dpPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(DateAwKer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DateAkKer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbJabatanPeru, 0, 265, Short.MAX_VALUE)
                            .addComponent(cmbNmPerusahaan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(dpPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addComponent(jScrollPane4)))
                    .addGroup(dpPersonalLayout.createSequentialGroup()
                        .addGroup(dpPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addComponent(jLabel19)
                            .addComponent(jLabel18))
                        .addGroup(dpPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(dpPersonalLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(dpPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dateOrgAk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dateOrgAw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(dpPersonalLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbNamaOraginsasi, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dpPersonalLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbJabatan, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(dpPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(dpPersonalLayout.createSequentialGroup()
                        .addGroup(dpPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(dpPersonalLayout.createSequentialGroup()
                                .addGroup(dpPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(44, 44, 44)
                                .addGroup(dpPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbSex, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(dpPersonalLayout.createSequentialGroup()
                                .addGroup(dpPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel1))
                                .addGap(48, 48, 48)
                                .addGroup(dpPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(dpPersonalLayout.createSequentialGroup()
                                        .addGroup(dpPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txtStatus, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cmbNegara, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(dateBirth, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cmbStatusKwn, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(dpPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(dpPersonalLayout.createSequentialGroup()
                                        .addGroup(dpPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel8))
                                        .addGap(18, 18, 18)
                                        .addComponent(txtPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(dpPersonalLayout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(dpPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txtbahsa)
                                            .addComponent(txtMail, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(dpPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cmbBahasa, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cmbMail, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnPhoto, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)))
                            .addComponent(jLabel24)
                            .addComponent(jLabel25))
                        .addGap(0, 20, Short.MAX_VALUE)))
                .addContainerGap())
        );
        dpPersonalLayout.setVerticalGroup(
            dpPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dpPersonalLayout.createSequentialGroup()
                .addGroup(dpPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dpPersonalLayout.createSequentialGroup()
                        .addGroup(dpPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(dpPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(dateBirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(dpPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cmbNegara, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(dpPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbStatusKwn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(dpPersonalLayout.createSequentialGroup()
                        .addGroup(dpPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(dpPersonalLayout.createSequentialGroup()
                                .addGroup(dpPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(cmbMail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(dpPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cmbBahasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8)))
                            .addGroup(dpPersonalLayout.createSequentialGroup()
                                .addComponent(txtMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtbahsa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(dpPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPhoto))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dpPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmbSex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dpPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dpPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dpPersonalLayout.createSequentialGroup()
                        .addGroup(dpPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbNamaOraginsasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addGap(19, 19, 19)
                        .addGroup(dpPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbJabatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGroup(dpPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dpPersonalLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(dpPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(dateOrgAw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(dpPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(dateOrgAk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel25)
                .addGroup(dpPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dpPersonalLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(dpPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(dpPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cmbNmPerusahaan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel20))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(dpPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(dpPersonalLayout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addComponent(jLabel23))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dpPersonalLayout.createSequentialGroup()
                                .addGroup(dpPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cmbJabatanPeru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel21))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(dpPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(DateAwKer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel22))
                                .addGap(7, 7, 7)
                                .addComponent(DateAkKer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(dpPersonalLayout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        btnSave.setText("CHECK");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnViewData.setText("NEXT");
        btnViewData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDataActionPerformed(evt);
            }
        });

        btnReset.setText("RESET");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        txtIdPersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdPersonalActionPerformed(evt);
            }
        });

        jLabel10.setText("ID CV Anda");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dpPersonal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtIdPersonal, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnSave, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel10)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnViewData, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnReset, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIdPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSave)
                        .addGap(18, 18, 18)
                        .addComponent(btnViewData)
                        .addGap(18, 18, 18)
                        .addComponent(btnReset))
                    .addComponent(dpPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbNamaOraginsasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbNamaOraginsasiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbNamaOraginsasiActionPerformed

    private void cmbNmPerusahaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbNmPerusahaanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbNmPerusahaanActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnViewDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnViewDataActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
       String mailnya = txtMail.getText(); String cmbMael = (String) cmbMail.getSelectedItem();String emainya = mailnya.concat(cmbMael); 
       String idOrgT = controller1.getAutoId1().toString();String idOrg = controller1.getLastId().toString(); 
       String idExp = controller1.getAutoId2().toString();String idExpW = controller1.getLastId2().toString();
//            controller.saveOrUpdate(txtIdPersonal.getText(), txtName.getText(), sg.getDateFormat(dateBirth), 
//                cmbNegara.getSelectedItem()+"", txtStatus.getText(), cmbSex.getSelectedItem()+"",
//                txtPhone.getText(), txtMail.getText(), txtPhone.getText());
//Organizationdetails(new BigDecimal(idorgdetail), organizationname, position, new Date(startdate), new Date(enddate), status, organization, personaldata);
         //controller.saveOrUpdate1(idOrgT, txtNamaOrga.getText(), txtJabatanOrg.getText(), sg.getDateFormat(dateOrgAw), sg.getDateFormat(dateOrgAk), "w", idOrg, txtIdPersonal.getText());
         //(BigDecimal idexpdetail, String status, String jobtitle, Date startdate, Date enddate, String namaperusahaan, Personaldata idpersonal, Workingexperience idworkingexperience)
         //controller.saveOrUpdate2(idExp, "w", txtJabatanPrus.getText(), sg.getDateFormat(DateAwKer), sg.getDateFormat(DateAkKer), txtNamaPerus.getText(), txtIdPersonal.getText(), idExpW);
         JOptionPane.showMessageDialog(this, pesan.save.getPesan(), "Save", JOptionPane.INFORMATION_MESSAGE);
        reset();
        PersonalDataView personalDataView = new PersonalDataView(factory);
         personalDataView.show();
         dpPersonal.add(personalDataView);
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtIdPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdPersonalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdPersonalActionPerformed

    private void txtbahsaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbahsaKeyTyped
        // TODO add your handling code here:
        sg.filterAngka(evt);
    }//GEN-LAST:event_txtbahsaKeyTyped

    private void cmbStatusKwnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbStatusKwnMouseEntered
        // TODO add your handling code here:
        txtStatus.setText((String) cmbStatusKwn.getSelectedItem());
    }//GEN-LAST:event_cmbStatusKwnMouseEntered

    private void cmbMailMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbMailMouseEntered
        // TODO add your handling code here:
        txtMail.setText((String) cmbMail.getSelectedItem());
    }//GEN-LAST:event_cmbMailMouseEntered

    private void cmbBahasaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbBahasaMouseEntered
        // TODO add your handling code here:
        txtbahsa.setText((String) cmbBahasa.getSelectedItem());
    }//GEN-LAST:event_cmbBahasaMouseEntered

    private void cmbNamaOraginsasiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbNamaOraginsasiMouseEntered
        // TODO add your handling code here:
        txtNamaOrga.setText((String) cmbNamaOraginsasi.getSelectedItem());
    }//GEN-LAST:event_cmbNamaOraginsasiMouseEntered

    private void cmbJabatanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbJabatanMouseEntered
        // TODO add your handling code here:
        txtJabatanOrg.setText((String) cmbJabatan.getSelectedItem());
    }//GEN-LAST:event_cmbJabatanMouseEntered

    private void cmbNmPerusahaanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbNmPerusahaanMouseEntered
        // TODO add your handling code here:
        txtNamaPerus.setText((String) cmbNmPerusahaan.getSelectedItem());
    }//GEN-LAST:event_cmbNmPerusahaanMouseEntered

    private void cmbJabatanPeruMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbJabatanPeruMouseEntered
        // TODO add your handling code here:
        txtJabatanPrus.setText((String) cmbJabatanPeru.getSelectedItem());
    }//GEN-LAST:event_cmbJabatanPeruMouseEntered


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXDatePicker DateAkKer;
    private org.jdesktop.swingx.JXDatePicker DateAwKer;
    private javax.swing.JButton btnPhoto;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnViewData;
    private javax.swing.JComboBox<String> cmbBahasa;
    private javax.swing.JComboBox<String> cmbJabatan;
    private javax.swing.JComboBox<String> cmbJabatanPeru;
    private javax.swing.JComboBox<String> cmbMail;
    private javax.swing.JComboBox<String> cmbNamaOraginsasi;
    private javax.swing.JComboBox<String> cmbNegara;
    private javax.swing.JComboBox<String> cmbNmPerusahaan;
    private javax.swing.JComboBox<String> cmbSex;
    private javax.swing.JComboBox<String> cmbStatusKwn;
    private org.jdesktop.swingx.JXDatePicker dateBirth;
    private org.jdesktop.swingx.JXDatePicker dateOrgAk;
    private org.jdesktop.swingx.JXDatePicker dateOrgAw;
    private javax.swing.JPanel dpPersonal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField txtIdPersonal;
    private javax.swing.JTextArea txtJabatanOrg;
    private javax.swing.JTextArea txtJabatanPrus;
    private javax.swing.JTextField txtMail;
    private javax.swing.JTextArea txtNamaOrga;
    private javax.swing.JTextArea txtNamaPerus;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtPhoto;
    private javax.swing.JTextField txtStatus;
    private javax.swing.JTextField txtbahsa;
    // End of variables declaration//GEN-END:variables

    public  void reset(){
        txtIdPersonal.setText(controller.getAutoId().toString());txtIdPersonal.setEnabled(true);
        txtJabatanPrus.setText("Jabatan anda di Perusahaan");
        txtJabatanOrg.setText("Jabatan anda di Organisasi");
        txtMail.setText("Email anda");txtNamaOrga.setText("Nama Organisasi yanga anda ikuti");
        txtNamaPerus.setText("Nama perusahaan");txtName.setText("Nama lengkap anda");
        txtPhone.setText("No Hp anda");txtPhoto.setText("photo ukuran max 500kb");txtStatus.setText("Status Kawin");
    }
}
