/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ProgrammingController;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import model.Programming;
import org.hibernate.SessionFactory;
import view.SerbaGuna.pesan;

/**
 *
 * @author chochong
 */
public class ProgrammingView extends javax.swing.JInternalFrame {

    private SerbaGuna sg;
    private TableRowSorter<TableModel> rowSorter;
    private final ProgrammingController controller;

    /**
     * Creates new form ProgrammingView
     */
    public ProgrammingView(SessionFactory sessionFactory) {
        initComponents();
        controller = new ProgrammingController(sessionFactory);
        bindingProgramming(controller.getAll());
        tblProgramming.setRowSorter(rowSorter);
        sg = new SerbaGuna();
        reset();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cmbKategori = new javax.swing.JComboBox<>();
        txtSearch = new javax.swing.JTextField();
        btnFind = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProgramming = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        txtProgrammingId = new javax.swing.JTextField();
        txtProgrammingName = new javax.swing.JTextField();
        jlProgrammingId = new javax.swing.JLabel();
        jlProgrammingName = new javax.swing.JLabel();
        btnDrop = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Master Programming");

        cmbKategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID Programming", "Programming Name" }));

        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        btnFind.setText("FIND");
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });

        tblProgramming.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblProgramming.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProgrammingMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblProgramming);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cmbKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFind)
                .addGap(25, 25, 25))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 581, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbKategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFind))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Detail", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 18))); // NOI18N
        jPanel2.setToolTipText("Detail");

        txtProgrammingId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProgrammingIdActionPerformed(evt);
            }
        });
        txtProgrammingId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtProgrammingIdKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtProgrammingIdKeyTyped(evt);
            }
        });

        txtProgrammingName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtProgrammingNameKeyTyped(evt);
            }
        });

        jlProgrammingId.setText("Programming Id       :");

        jlProgrammingName.setText("Programming Name :");

        btnDrop.setText("DROP");
        btnDrop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDropActionPerformed(evt);
            }
        });

        btnSave.setText("SAVE");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlProgrammingName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlProgrammingId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtProgrammingName, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                    .addComponent(txtProgrammingId))
                .addGap(72, 72, 72)
                .addComponent(btnSave)
                .addGap(25, 25, 25)
                .addComponent(btnDrop)
                .addGap(50, 50, 50))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlProgrammingId)
                    .addComponent(txtProgrammingId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlProgrammingName)
                    .addComponent(txtProgrammingName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDrop)
                    .addComponent(btnSave))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Untuk melakukan pencarian dari kategori dengan menekan tombol enter dan menampilkan seluruh data saat
     * textfield search dikosongkan
     * @param evt (KeyEvent)
     */
    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (!txtSearch.getText().equals("")) {
                String text = txtSearch.getText();
                if (text.trim().length() == 0) {
                    rowSorter.setRowFilter(null);
                    } else {
                    rowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + text, cmbKategori.getSelectedIndex()+1));
                }  
            }
        }
        if (txtSearch.getText().equals("")) {
            bindingProgramming(controller.getAll());
        }
    }//GEN-LAST:event_txtSearchKeyReleased

    /**
     * Melakukan pencarian dengan menggunakan button find
     * @param evt (ActionEvent)
     */
    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
        if (!txtSearch.getText().equals("")) {
            String text = txtSearch.getText();
            if (text.trim().length() == 0) {
                rowSorter.setRowFilter(null);
                } else {
                rowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + text, cmbKategori.getSelectedIndex()+1));
            }  
        }
    }//GEN-LAST:event_btnFindActionPerformed

    private void txtProgrammingIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProgrammingIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProgrammingIdActionPerformed

    private void txtProgrammingIdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProgrammingIdKeyReleased

    }//GEN-LAST:event_txtProgrammingIdKeyReleased

    private void txtProgrammingIdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProgrammingIdKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProgrammingIdKeyTyped

    private void txtProgrammingNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProgrammingNameKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProgrammingNameKeyTyped

    /**
     * Untuk menghapus data dengan menggunakan button drop
     * @param evt (ActionEvent)
     */
    private void btnDropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDropActionPerformed
        int messageBox = JOptionPane.showConfirmDialog(this, "Apakah anda yakin ?", "Delete", JOptionPane.YES_NO_OPTION ,JOptionPane.WARNING_MESSAGE);
        if(messageBox == JOptionPane.YES_OPTION){
            controller.delete(txtProgrammingId.getText());
            JOptionPane.showMessageDialog(this, pesan.delete.getPesan());
            bindingProgramming(controller.getAll());
            reset();
        }
        if(messageBox == JOptionPane.NO_OPTION){
            JOptionPane.showMessageDialog(this, pesan.cancel.getPesan());
        }
    }//GEN-LAST:event_btnDropActionPerformed

    /**
     * Untuk menyimpan dan memperbaharui data dengan menggunakan button save
     * @param evt (ActionEvent)
     */
    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        controller.saveOrUpdate(txtProgrammingId.getText(), txtProgrammingName.getText());
        if (btnDrop.isEnabled()) {
            JOptionPane.showMessageDialog(this, pesan.update.getPesan(), "Update", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, pesan.save.getPesan(), "Save", JOptionPane.INFORMATION_MESSAGE);
        }
        bindingProgramming((List<Object>) controller.getAll());
        reset();
    }//GEN-LAST:event_btnSaveActionPerformed

    /**
     * Mengambil data dari baris yang di klik oleh mouse
     * @param evt (MouseEvent)
     */
    private void tblProgrammingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProgrammingMouseClicked
         // TODO add your handling code here:
        int row = tblProgramming.getSelectedRow();
        txtProgrammingId.setText(tblProgramming.getValueAt(row, 1).toString());
        txtProgrammingName.setText(tblProgramming.getValueAt(row, 2).toString());
        edit();
    }//GEN-LAST:event_tblProgrammingMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDrop;
    private javax.swing.JButton btnFind;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cmbKategori;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlProgrammingId;
    private javax.swing.JLabel jlProgrammingName;
    private javax.swing.JTable tblProgramming;
    private javax.swing.JTextField txtProgrammingId;
    private javax.swing.JTextField txtProgrammingName;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables

    /**
     * Untuk menampilkan seluruh data ke dalam tabel
     * @param programmings (List<Object>) data yang akan dimasukan ke tabel
     */
    private void bindingProgramming(List<Object> programmings) {
        String[] header = {"No", "ID Programming", "Programming Skill"};
        String[][] data = new String[programmings.size()][header.length];
        int i = 0;
        for (Object object : programmings) {
            Programming programming = (Programming) object;
            data[i][0] = (i + 1) + "";
            data[i][1] = programming.getIdprogramming().toString();
            data[i][2] = programming.getProgramminglanguage();
            i++;
        }
        tblProgramming.setModel(new DefaultTableModel(data, header));
        this.rowSorter = new TableRowSorter<>(tblProgramming.getModel());
        reset();
    }

    /**
     * Menampilkan ID terakhir di textfield programmingId dan mengaktifkan serta menghilangkan kemampuan meng-edit 
     * textfield tersebut, menonaktifkan button drop, mengosongkan textfield programmingName
     */
    public void reset() {
        txtProgrammingId.setText(controller.getAutoId() + "");
        txtProgrammingId.setEnabled(true);
        tblProgramming.setRowSorter(rowSorter);
        btnDrop.setEnabled(false);
        txtProgrammingId.setEditable(false);
        txtProgrammingName.setText("");
    }

    /**
     * menonaktifkan texfield programmingId dan button drop
     */
    public void edit() {
        txtProgrammingId.setEnabled(false);
        btnDrop.setEnabled(true);
    }
}
