/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author chochong
 */
public class ProgrammingView extends javax.swing.JInternalFrame {

    /**
     * Creates new form ProgrammingView
     */
    public ProgrammingView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cmbKategoriCountry = new javax.swing.JComboBox<>();
        txtFindCountry = new javax.swing.JTextField();
        btnFindC = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        txtProgrammingid = new javax.swing.JTextField();
        txtProgrammingName = new javax.swing.JTextField();
        jlProgrammingId = new javax.swing.JLabel();
        jlProgrammingName = new javax.swing.JLabel();
        btnDropC = new javax.swing.JButton();
        btnSaveC = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Master Programming");

        cmbKategoriCountry.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", " ", " " }));

        txtFindCountry.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFindCountryKeyReleased(evt);
            }
        });

        btnFindC.setText("FIND");
        btnFindC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindCActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cmbKategoriCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFindCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFindC)
                .addGap(25, 25, 25))
            .addComponent(jScrollPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbKategoriCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFindCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFindC))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Detail", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 18))); // NOI18N
        jPanel2.setToolTipText("Detail");

        txtProgrammingid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProgrammingidActionPerformed(evt);
            }
        });
        txtProgrammingid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtProgrammingidKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtProgrammingidKeyTyped(evt);
            }
        });

        txtProgrammingName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtProgrammingNameKeyTyped(evt);
            }
        });

        jlProgrammingId.setText("Programming Id       :");

        jlProgrammingName.setText("Programming Name :");

        btnDropC.setText("DROP");
        btnDropC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDropCActionPerformed(evt);
            }
        });

        btnSaveC.setText("SAVE");
        btnSaveC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlProgrammingName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlProgrammingId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtProgrammingName, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                    .addComponent(txtProgrammingid))
                .addGap(72, 72, 72)
                .addComponent(btnDropC)
                .addGap(18, 18, 18)
                .addComponent(btnSaveC)
                .addGap(57, 57, 57))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlProgrammingId)
                    .addComponent(txtProgrammingid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlProgrammingName)
                    .addComponent(txtProgrammingName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDropC)
                    .addComponent(btnSaveC))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFindCountryKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFindCountryKeyReleased
        // TODO add your handling code here:
        //                if (txtFindCountry.getText().equals("")) {
            //                bindingCountries(controller.getAll());
            //            }else if (!txtFindCountry.getText().equalsIgnoreCase("")){
            //                btnFindC.setEnabled(true);
            //            }
        //        if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
            ///*use inisialisasi string categori*/
            ////            if (cmbKategoriCountry.getSelectedItem().equals("Region Id")){
                ////            bindingCountries(controller.search("regionId", (txtFindCountry.getText())));
                ////            } else if (cmbKategoriCountry.getSelectedItem().equals("Region Name")){
                ////            bindingCountries(controller.search("regionName", txtFindCountry.getText()));
                ////            }else if (cmbKategoriCountry.getSelectedItem().equals("Country Id")){
                ////            bindingCountries(controller.search("countryId", txtFindCountry.getText()));
                ////            }else if (cmbKategoriCountry.getSelectedItem().equals("Country Name"))
            ////            bindingCountries(controller.search("countryName", txtFindCountry.getText()));
            ///*use array*/  //bindingCountries(controller.search(cmbItem[cmbKategoriCountry.getSelectedIndex()], txtFindCountry.getText()));
            ///*use enum*/  bindingCountries(controller.searchCountry((String) cmbKategoriCountry.getSelectedItem(), txtFindCountry.getText()));
            ///*use rowSorter*/
            ////            String text = txtFindCountry.getText();
            ////            if (text.trim().length() == 0) {
                ////                rowSorter.setRowFilter(null);
                ////            } else {
                ////                rowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + text, cmbKategoriCountry.getSelectedIndex() + 1));
                ////            }
            //        }

    }//GEN-LAST:event_txtFindCountryKeyReleased

    private void btnFindCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindCActionPerformed
        // TODO add your handling code here:
        //        if (!txtFindCountry.getText().equalsIgnoreCase("")) {
            /*use inisialisasi string categori*/
            //            if (cmbKategoriCountry.getSelectedItem().equals("Region Id")){
                //            bindingCountries(controller.search("regionId", new BigDecimal(txtFindCountry.getText())));
                //            } else if (cmbKategoriCountry.getSelectedItem().equals("Region Name")){
                //            bindingCountries(controller.search("regionName", txtFindCountry.getText()));
                //            }else if (cmbKategoriCountry.getSelectedItem().equals("Country Id")){
                //            bindingCountries(controller.search("countryId", txtFindCountry.getText()));
                //            }else if (cmbKategoriCountry.getSelectedItem().equals("Country Name"))
            //            bindingCountries(controller.search("countryName", txtFindCountry.getText()));

            /*use array*/  //bindingCountries(controller.search(cmbItem[cmbKategoriCountry.getSelectedIndex()], txtFindCountry.getText()));
            // /*use enum*/  bindingCountries(controller.searchCountry((String) cmbKategoriCountry.getSelectedItem(), txtFindCountry.getText()));

            /*use rowSorter*/
            //            String text = txtFindCountry.getText();
            //            if (text.trim().length() == 0) {
                //                rowSorter.setRowFilter(null);
                //            } else {
                //                rowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + text, cmbKategoriCountry.getSelectedIndex() + 1));
                //            }
            //        JOptionPane.showMessageDialog(this,
                //        pesan.find.getPesan(), "Search",
                //        JOptionPane.INFORMATION_MESSAGE);
            //        }
    }//GEN-LAST:event_btnFindCActionPerformed

    private void txtProgrammingidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProgrammingidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProgrammingidActionPerformed

    private void txtProgrammingidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProgrammingidKeyReleased
        // TODO add your handling code here:
//        if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
//            if (!txtCountryId.getText().equals("") ){
//                sf.filterAngka(evt);
//            }
//        }
    }//GEN-LAST:event_txtProgrammingidKeyReleased

    private void txtProgrammingidKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProgrammingidKeyTyped
        // TODO add your handling code here:
        //        ss.filterAngka(evt);
    }//GEN-LAST:event_txtProgrammingidKeyTyped

    private void txtProgrammingNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProgrammingNameKeyTyped
        // TODO add your handling code here:
//        sf.filterPass(evt);
    }//GEN-LAST:event_txtProgrammingNameKeyTyped

    private void btnDropCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDropCActionPerformed
        // TODO add your handling code here:
        //        int response = JOptionPane.showConfirmDialog(null, "Do you really want to delete?","Pertanyaan",JOptionPane.YES_NO_OPTION);
        //        Country country = new Country();
        //        country = new Country(txtCountryId.getText());
        //        if (response == JOptionPane.YES_OPTION) {
            //        controller.delete(country);
            //        JOptionPane.showMessageDialog(this, inf.delete.getPesan(), "Delete", JOptionPane.INFORMATION_MESSAGE);
            //        bindingCountries(controller.getAll());
            //        cmbRegionId.setSelectedIndex(0);
            //        }else if (response == JOptionPane.NO_OPTION) {
            //            JOptionPane.showMessageDialog(this, inf.cancle.getPesan(), "Delete", JOptionPane.INFORMATION_MESSAGE);
            //        }
    }//GEN-LAST:event_btnDropCActionPerformed

    private void btnSaveCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveCActionPerformed
        // TODO add your handling code here:
        //        String abcd = cmbRegionId.getSelectedItem()+"";
        //        String subRegionId = abcd.substring(0,1);
        //        Country country = new Country();
        //        country = new Country(txtCountryId.getText().toUpperCase());
        //        country.setCountryName(txtCountryName.getText());
        //        Region region = new Region(new BigDecimal(subRegionId));
        //        country.setRegionId(region);
        //        boolean isUpdate = false;
        //        if(!txtCountryId.isEnabled()){
            //            isUpdate = true;
            //        }
        //        if (isUpdate) {
            //            controller.saveOrUpdate(country);        //txtCountryId.getText(),txtCountryName.getText(),  subRegionId, false);
        //            JOptionPane.showMessageDialog(this, pesan.update.getPesan(), "Update", JOptionPane.INFORMATION_MESSAGE);
        //            bindingCountries(controller.getAll());}
        //        else {controller.saveOrUpdate(country);    //txtCountryId.getText(),txtCountryName.getText(), subRegionId, true);
        //            JOptionPane.showMessageDialog(this, pesan.save.getPesan(), "Simpan", JOptionPane.INFORMATION_MESSAGE);
        //            bindingCountries(controller.getAll());
        //            txtCountryId.setEditable(true);
        //         }
        //cmbRegionId.setSelectedIndex(0);
    }//GEN-LAST:event_btnSaveCActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDropC;
    private javax.swing.JButton btnFindC;
    private javax.swing.JButton btnSaveC;
    private javax.swing.JComboBox<String> cmbKategoriCountry;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel jlProgrammingId;
    private javax.swing.JLabel jlProgrammingName;
    private javax.swing.JTextField txtFindCountry;
    private javax.swing.JTextField txtProgrammingName;
    private javax.swing.JTextField txtProgrammingid;
    // End of variables declaration//GEN-END:variables
}
